version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Your_password123' -Q 'SELECT 1' -C"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./mssql-data:/var/opt/mssql
    restart: unless-stopped

  backend:
    build:
      context: ./Projekt-RSI-1-BackEnd
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DBConnection: "Server=mssql;Database=PROJEKT-RSI-1;User Id=sa;Password=Your_password123;TrustServerCertificate=True;"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /app/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: "CertHaslo"
    volumes:
      - ./certs/backend.pfx:/app/aspnetapp.pfx:ro
    depends_on:
      - mssql
    restart: unless-stopped

  exchanger:
    build:
      context: ./Projekt-RSI-1-Exchanger
      dockerfile: Dockerfile
    ports:
      - "8180:8180"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DBConnection: "Server=mssql;Database=PROJEKT-RSI-1;User Id=sa;Password=Your_password123;TrustServerCertificate=True;"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /app/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: "CertHaslo"
    volumes:
      - ./certs/backend.pfx:/app/aspnetapp.pfx:ro
    depends_on:
      - mssql
    restart: unless-stopped

  frontend:
    build:
      context: ./Projekt-RSI-1-FrontEnd
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      PORT: "80"
      HOST: "0.0.0.0"
    depends_on:
      - backend
      - exchanger
    restart: unless-stopped

volumes:
  mssql-data:
    driver: local
