version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      MSSQL_SA_PASSWORD: "MojeNoweHaslo123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./mssql-data:/var/opt/mssql/data
    restart: unless-stopped

  backend:
    build:
      context: ./Projekt-RSI-1-BackEnd
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DBConnection: "Server=mssql;Database=PROJEKT-RSI-1;User Id=sa;Password=MojeNoweHaslo123!;TrustServerCertificate=True;"
      Keys__ApiKey: "GIGATAJNYKLUCZDOAPI"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /app/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: "YourPfxPassword"
    volumes:
      - ./certs/backend.pfx:/app/aspnetapp.pfx:ro
    depends_on:
      - mssql
    restart: unless-stopped

  exchanger:
    build:
      context: ./Projekt-RSI-1-Exchanger
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_Kestrel__Certificates__Default__Path: /app/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: "YourPfxPassword"
    volumes:
      - ./certs/backend.pfx:/app/aspnetapp.pfx:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./Projekt-RSI-1-FrontEnd
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      HOST: "0.0.0.0"
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    volumes:
      # Montujemy certyfikaty do niezależnego folderu w roocie systemu kontenera
      - ./certs:/certs:ro
    depends_on:
      - backend
      - exchanger
    restart: unless-stopped
    

volumes:
  mssql-data:
    driver: local
